### ISSUE TITLE
I can "save" the playlist in my youtube channel?

### ISSUE THREAD

**Issue by 9acca9** [MacielG1/Youtube_Playlist_Manager#1]
hi.
thanks for share your work!
I was searching exactly this!
(create a complete playlist from all the videos of a youtube channel)

I just will like to add the create playlist to my channel but i dont find in any place the "like" playlist or "save" playlist in the youtube web. And i will like to save the created playlist to my youtube channel.
It is possible?

Thanks!
EDIT: by the way is possible to play random in your web app?

**Comment by MacielG1** [comment]
It's not possible to save a playlist to YouTube. What you can do is click on the 'Open on YouTube' icon and manage it there, but I don't think YouTube allows saving those types of playlists. 
Regarding the shuffle functionality, it could be something that we add in the future.
